s = input("введи строку: ")
s = (s.replace('a', '')
     .replace('A', '')
     .replace('e', '')
     .replace('E', '')
     .replace('i', '')
     .replace('I', '')
     .replace('o', '')
     .replace('O', '')
     .replace('u', '')
     .replace('U', ''))
print("результат:", s)
